#!/usr/bin/env ruby

# Triggers a build that builds a docker image and ships to quay.io

require 'json'
require 'net/http'

def post(uri, body, token)
  http = Net::HTTP.new(uri.host, uri.port)
  http.use_ssl = true

  req = Net::HTTP::Post.new(uri.path)
  req['Authorization'] = "token #{token}"
  req['Content-Type'] = 'application/json'
  req['Travis-API-Version'] = '3'
  req.body = JSON.dump(body)

  http.request(req)
end

token = ENV['TRAVIS_API_TOKEN']
repo  = ENV['TRAVIS_REPO_SLUG']

uri = URI.parse("https://api.travis-ci.com/repo/#{repo.sub('/', '%2F')}/requests")

body = {
  request: {
    branch: 'ship_docker',
    message: "build and ship docker image, triggered by build ##{ENV['TRAVIS_BUILD_NUMBER']} (#{ENV['TRAVIS_COMMIT']})",
    config: {
      merge_mode: 'merge',
      name: ':ship: docker image',
      git: {
        depth: false
      },
      before_script: [
        'curl -s https://raw.githubusercontent.com/travis-ci/build-configs/master/ship_docker/Makefile > Makefile'
      ],
      script: [
        'make ship'
      ]
    }
  }
}

puts 'triggering a new build to build and ship docker image ...'
res = post(uri, body, token)
p res.code.to_i
puts res.body
